.TH "Cpu_List" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cpu_List \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main_header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBdata\fP"
.br
.ti -1c
.RI "\fBCpu_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for creating linked list for cpu usage 
.SH "Field Documentation"
.PP 
.SS "float* data"

.SS "\fBCpu_list\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
