.TH "Device_Collection" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Device_Collection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBDevices\fP \fBdevices\fP"
.br
.ti -1c
.RI "\fBD_Collection\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBD_Collection\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
doubly linked list for devices 
.SH "Field Documentation"
.PP 
.SS "\fBDevices\fP devices"

.SS "\fBD_Collection\fP* next"

.SS "\fBD_Collection\fP* prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
