.TH "NetMem_list" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NetMem_list \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main_header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBdata\fP [2]"
.br
.ti -1c
.RI "\fBNetMem_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure for creating linked list for memory usage and network usage 
.SH "Field Documentation"
.PP 
.SS "float data[2]"

.SS "\fBNetMem_list\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
