.TH "Interrupt_Collection" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interrupt_Collection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBInterrupts\fP \fBinterrupts\fP"
.br
.ti -1c
.RI "\fBI_Collection\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBI_Collection\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBInterrupts\fP interrupts"

.SS "\fBI_Collection\fP* next"

.SS "\fBI_Collection\fP* prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
