.TH "Mega_Data" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mega_Data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main_header\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float * \fBcpu_stats\fP"
.br
.ti -1c
.RI "float * \fBmem_stats\fP"
.br
.ti -1c
.RI "float * \fBnet_stats\fP"
.br
.ti -1c
.RI "\fBT_Collection\fP * \fBtask_list\fP"
.br
.ti -1c
.RI "\fBD_Collection\fP * \fBdevice_list\fP"
.br
.ti -1c
.RI "\fBI_Collection2\fP * \fBinterrupts_list\fP"
.br
.ti -1c
.RI "\fBMega_Data\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float* cpu_stats"

.SS "\fBD_Collection\fP* device_list"

.SS "\fBI_Collection2\fP* interrupts_list"

.SS "float* mem_stats"

.SS "float* net_stats"

.SS "\fBMega_Data\fP* next"

.SS "\fBT_Collection\fP* task_list"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
