.TH "Task_Collection" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Task_Collection \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTask\fP \fBtask\fP"
.br
.ti -1c
.RI "\fBT_Collection\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBT_Collection\fP * \fBprev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBT_Collection\fP* next"

.SS "\fBT_Collection\fP* prev"

.SS "\fBTask\fP task"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
