.TH "Unification" 3 "Wed Apr 14 2021" "Version 1.1" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unification \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <common\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBTask\fP \fBtask\fP"
.br
.ti -1c
.RI "\fBNetwork\fP \fBnetwork\fP"
.br
.ti -1c
.RI "\fBMemory_usage\fP \fBmemory_usage\fP"
.br
.ti -1c
.RI "\fBInterrupts\fP \fBinterrupts\fP"
.br
.ti -1c
.RI "\fBInterrupts_send\fP \fBinterrupts_send\fP"
.br
.ti -1c
.RI "\fBDevices\fP \fBdevices\fP"
.br
.ti -1c
.RI "char \fBconformation\fP [64]"
.br
.ti -1c
.RI "char \fBdata_pack\fP [1024]"
.br
.in -1c
.SH "Detailed Description"
.PP 
union data structure that uses the same memory space for all elements 
.SH "Field Documentation"
.PP 
.SS "char conformation[64]"

.SS "char data_pack[1024]"

.SS "\fBDevices\fP devices"

.SS "\fBInterrupts\fP interrupts"

.SS "\fBInterrupts_send\fP interrupts_send"

.SS "\fBMemory_usage\fP memory_usage"

.SS "\fBNetwork\fP network"

.SS "\fBTask\fP task"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
